version: '3.9'

services:
  # Booking Service
  booking_service:
    build:
      context: ./booking_service
    container_name: booking_service
    ports:
      - "8081:80"  # Map container port 80 to host port 8081
    depends_on:
      - booking_db  # Ensure booking_db is up before starting this service
    volumes:
      - ./booking_service:/var/www/html

  # User Service
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8082:80"  # Map container port 80 to host port 8082
    depends_on:
      - user_db  # Ensure user_db is up before starting this service
    volumes:
      - ./user_service:/var/www/html

  # Notification Service
  notification_service:
    build:
      context: ./notification_service
    container_name: notification_service
    ports:
      - "8083:80"  # Map container port 80 to host port 8083
    depends_on:
      - rabbitmq  # Ensure rabbitmq is up before starting this service
    volumes:
      - ./notification_service:/var/www/html

  # MySQL Database for Booking Service
  booking_db:
    image: mysql:8.0
    container_name: booking_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=booking
    ports:
      - "3307:3306"  # Expose MySQL database on port 3307
    volumes:
      - booking_db_data:/var/lib/mysql  # Persist MySQL data
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "booking_db" ]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  # PostgreSQL Database for User Service
  user_db:
    image: postgres:13
    container_name: user_db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user
    ports:
      - "5433:5432"  # Expose Postgres database on port 5433
    volumes:
      - user_db_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  # RabbitMQ for Notification Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management port


volumes:
  booking_db_data:
  user_db_data: